api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
    
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
   ##grantgoal urls 
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('new/grantgoal/', views.NewGrantGoal.as_view(), name="create_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),

    ##subgrantgoal urls
    path('list/subgrantgoal/', views.ListSubGrantGoal.as_view(), name="list_sgg"),
    path('detail/subgrantgoal/<int:pk>/', views.DetailSubGrantGoal.as_view(), name="detail_sgg"),
    path('new/subgrantgoal/', views.NewSubGrantGoal.as_view(), name="create_sgg"),
    path('update/subgrantgoal/<int:pk>/', views.UpdateSubGrantGoal.as_view(), name="update_sgg"),
    path('delete/subgrantgoal/<int:pk>/', views.DeleteSubGrantGoal.as_view(), name="delete_sgg"),

    ###goals urls
    path('list/goal/', views.ListGoal.as_view(), name="list_g"),
    path('detail/goal/<int:pk>/', views.DetailGoal.as_view(), name="detail_g"),
    path('new/goal/', views.NewGoal.as_view(), name="create_g"),
    path('update/goal/<int:pk>/', views.UpdateGoal.as_view(), name="update_g"),
    path('delete/goal/<int:pk>/', views.DeleteGoal.as_view(), name="delete_g"),

    ###Issues urls
    path('list/issue/', views.ListIssues.as_view(), name="list_i"),
    path('detail/issue/<int:pk>/', views.DetailIssue.as_view(), name="detail_i"),
    path('new/issue/', views.NewIssue.as_view(), name="create_i"),
    path('update/Issue/<int:pk>/', views.UpdateIssue.as_view(), name="update_i"),
    path('delete/Issue/<int:pk>/', views.DeleteIssue.as_view(), name="delete_i"),

    ###Area urls
    path('list/area/', views.ListArea.as_view(), name="list_a"),
    path('detail/area/<int:pk>/', views.DetailArea.as_view(), name="detail_a"),
    path('new/area/', views.NewArea.as_view(), name="create_a"),
    path('update/area/<int:pk>/', views.UpdateArea.as_view(), name="update_a"),
    path('delete/area/<int:pk>/', views.DeleteArea.as_view(), name="delete_a"),

]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),

    path('list/profile/', views.ListProfile.as_view(),name='list_profile'),
    path('detail/profile/<int:pk>/', views.DetailProfile.as_view(),name='detail_profile'),
]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <div class="row">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">PEM</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:list_a' %}">Area</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  GrantGoal Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'core:list_gg' %}">Grant Goals List</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:create_gg' %}">New Grant Goal</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  SubGrantGoal Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'core:list_sgg' %}">Sub GrantGoal List</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:create_sgg' %}">New Sub GrantGoal</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Goal Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'core:list_g' %}">Goal List</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:create_g' %}">New Goal</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Issue Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'core:list_i' %}">Issue List</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:create_i' %}">New Issue</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
            <ul class="navbar-nav me-right mb-2 mb-lg-0" style="padding-right: 2%;">
              <li><a class="dropdown-item" href="{% url 'home:logout' %}" style="padding-right: 2%;">| Logout </a></li>
              <li><a class="dropdown-item" style="margin-left:2% ;" href=""></a> | {{ request.user }} |</li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    </div>
    <hr>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          {% block content %}
          {% endblock content %}
        </div>
        <div class="col-2"></div>
    </div>
    <hr>
    <div class="row">
          <footer class="bg-body-tertiary text-center text-lg-start">
            <!-- Grid container -->
            <div class="container p-4">
              <!--Grid row-->
              <div class="row">
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                  <h5 class="text-uppercase">Footer text</h5>
          
                  <p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                    molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                    voluptatem veniam, est atque cumque eum delectus sint!
                  </p>
                </div>
                <!--Grid column-->
          
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                  <h5 class="text-uppercase">Footer text</h5>
          
                  <p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                    molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                    voluptatem veniam, est atque cumque eum delectus sint!
                  </p>
                </div>
                <!--Grid column-->
              </div>
              <!--Grid row-->
            </div>
            <!-- Grid container -->
          
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
              © 2020 Copyright:
              <a class="text-body" href="https://mdbootstrap.com/">MDBootstrap.com</a>
            </div>
            <!-- Copyright -->
          </footer>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>