api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
    
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
   ##grantgoal urls 
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('new/grantgoal/', views.NewGrantGoal.as_view(), name="create_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),

    ##subgrantgoal urls
    path('list/subgrantgoal/', views.ListSubGrantGoal.as_view(), name="list_sgg"),
    path('detail/subgrantgoal/<int:pk>/', views.DetailSubGrantGoal.as_view(), name="detail_sgg"),
    path('new/subgrantgoal/', views.NewSubGrantGoal.as_view(), name="create_sgg"),
    path('update/subgrantgoal/<int:pk>/', views.UpdateSubGrantGoal.as_view(), name="update_sgg"),
    path('delete/subgrantgoal/<int:pk>/', views.DeleteSubGrantGoal.as_view(), name="delete_sgg"),

    ###goals urls
    path('list/goal/', views.ListGoal.as_view(), name="list_g"),
    path('detail/goal/<int:pk>/', views.DetailGoal.as_view(), name="detail_g"),
    path('new/goal/', views.NewGoal.as_view(), name="create_g"),
    path('update/goal/<int:pk>/', views.UpdateGoal.as_view(), name="update_g"),
    path('delete/goal/<int:pk>/', views.DeleteGoal.as_view(), name="delete_g"),

    ###Issues urls
    path('list/issue/', views.ListIssues.as_view(), name="list_i"),
    path('detail/issue/<int:pk>/', views.DetailIssue.as_view(), name="detail_i"),
    path('new/issue/', views.NewIssue.as_view(), name="create_i"),
    path('update/Issue/<int:pk>/', views.UpdateIssue.as_view(), name="update_i"),
    path('delete/Issue/<int:pk>/', views.DeleteIssue.as_view(), name="delete_i"),

    ###Area urls
    path('list/area/', views.ListArea.as_view(), name="list_a"),
    path('detail/area/<int:pk>/', views.DetailArea.as_view(), name="detail_a"),
    path('new/area/', views.NewArea.as_view(), name="create_a"),
    path('update/area/<int:pk>/', views.UpdateArea.as_view(), name="update_a"),
    path('delete/area/<int:pk>/', views.DeleteArea.as_view(), name="delete_a"),

]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta

# Create your models here.

CHOICES_LEVEL = [
    ("HEIGHT","MG"),
    ("MIDDLE", "MD"),
    ("LOW","LW")
]

CHOICES_STATE = [
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN")
]

class GrantGoal(models.Model):
    ggname= models.CharField(max_length=64, default= "Generic Grand Goal")
    description = models.CharField(max_length=128, default='Generic Grant Goal description')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=True, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.ggname
    
@receiver(post_save, sender=GrantGoal)
def auto_final_date_GG(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date == '':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()

class Area(models.Model):
    area_name = models.CharField(max_length=32, default="Generic Area")
    description = models.CharField(max_length=128, default="Generic Activities")

    def __str__(self):
        return self.area_name


CHOICES_LEVEL_SUB = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_SUB = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class SubGrantGoal(models.Model):
    sggname = models.CharField(max_length=64, default="Generic Sub Grant Goal")
    description = models.CharField(max_length=128, default="Generic Sub Grant Goal description")
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    grantgoal = models.ForeignKey(GrantGoal, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_SUB)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_SUB)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.sggname


@receiver(post_save, sender=SubGrantGoal)
def auto_final_date_SGG(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()






CHOICES_LEVEL_GOAL = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_GOAL = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class Goal(models.Model):
    goalname = models.CharField(max_length=64, default="Generic Goal")
    description = models.CharField(max_length=128, default="Generic Goal description")
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subgrantgoal = models.ForeignKey(SubGrantGoal, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_GOAL)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_GOAL)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.goalname


@receiver(post_save, sender=Goal)
def auto_final_date_G(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()





CHOICES_LEVEL_ISSUE = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_ISSUE = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class Issue(models.Model):
    issuename = models.CharField(max_length=64, default="Generic Issue")
    description = models.CharField(max_length=128, default="Generic Issue description")
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_ISSUE)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_ISSUE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.issuename



@receiver(post_save, sender=Issue)
def auto_final_date_I(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()

core/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .forms import NewGrantGoalForm, UpdateGrantGoalForm

# Create your views here.

from core import models
from core import forms

### CRUD GG


### CREATE
class NewGrantGoal(generic.CreateView):
    template_name = 'core/grantgoal/create_gg.html'
    model = models.GrantGoal
    form_class = NewGrantGoalForm
    success_url = reverse_lazy('core:list_gg')

### RETRIEVE
### List
class ListGrantGoal(generic.View):
    template_name = "core/grantgoal/list_gg.html"
    context = {}

    def get(self, request):
        self.context = {
            "grantgoals": models.GrantGoal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)

### Detail
class DetailGrantGoal(generic.View):
    template_name = "core/grantgoal/detail_gg.html"
    context = {}

    def get(self, request,pk):
        self.context = {
            "grantgoals": models.GrantGoal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

### UPDATE
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/grantgoal/update_gg.html"
    model = models.GrantGoal
    form_class = UpdateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")

### DELETE
class DeleteGrantGoal(generic.CreateView):
    template_name = 'core/grantgoal/delete_gg.html'
    model = models.GrantGoal
    success_url = reverse_lazy('core:list.gg')


### CRUD SUBGG

### CREATE
class NewSubGrantGoal(generic.CreateView):
    template_name = "core/subgrantgoal/create_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.NewSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")

### RETRIEVE
### List
class ListSubGrantGoal(generic.ListView):
    template_name = "core/subgrantgoal/list_sgg.html"
    queryset = models.SubGrantGoal.objects.filter(status=True)

### Detail
class DetailSubGrantGoal(generic.DetailView):
    template_name = "core/subgrantgoal/detail_sgg.html"
    model = models.SubGrantGoal
    
### UPDATE
class UpdateSubGrantGoal(generic.UpdateView):
    template_name = "core/subgrantgoal/update_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.UpdateSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")

### DELETE
class DeleteSubGrantGoal(generic.DeleteView):
    template_name = "core/subgrantgoal/delete_sgg.html"
    model = models.SubGrantGoal
    success_url = reverse_lazy("core:list_sgg")



# # # # #  C R U D G O A L S # # # # #


# # # C R E A T E # # #
class NewGoal(generic.CreateView):
    template_name = 'core/goal/create_g.html'
    model = models.Goal
    form_class = forms.NewGoalForm
    success_url = reverse_lazy('core:list_g')

# # # R E T R I E V E # # #
# # List
class ListGoal(generic.ListView):
    template_name = "core/goal/list_g.html"
    queryset = models.Goal.objects.filter(status=True)

# # Detail
class DetailGoal(generic.DetailView):
    template_name = "core/goal/detail_g.html"
    model = models.Goal

# # # U P D A T E # # #
class UpdateGoal(generic.UpdateView):
    template_name = "core/goal/update_g.html"
    model = models.SubGrantGoal
    form_class = forms.UpdateGoalForm
    success_url = reverse_lazy("core:list_g")


# # # D E L E T E # # #
class DeleteGoal(generic.DeleteView):
    template_name = "core/goal/delete_g.html"
    model = models.Goal
    success_url = reverse_lazy("core:list_g")


# # # # #  C R U D I S S U E S  # # # # #


# # # C R E A T E # # #
class NewIssue(generic.CreateView):
    template_name = 'core/issue/create_i.html'
    model = models.Issue
    form_class = forms.NewIssueForm
    success_url = reverse_lazy('core:list_i')

# # # R E T R I E V E # # #
# # List
class ListIssues(generic.ListView):
    template_name = "core/issue/list_i.html"
    queryset = models.Issue.objects.filter(status=True)

# # Detail
class DetailIssue(generic.DetailView):
    template_name = "core/issue/detail_i.html"
    model = models.Issue


# # # U P D A T E # # #

class UpdateIssue(generic.UpdateView):
    template_name = "core/issue/update_i.html"
    model = models.Issue
    form_class = forms.UpdateIssueForm
    success_url = reverse_lazy("core:list_i")

# # # D E L E T E # # #
class DeleteIssue(generic.DeleteView):
    template_name = "core/issue/delete_i.html"
    model = models.Issue
    success_url = reverse_lazy("core:list_i")


# # # # #  C R U D A R E A S # # # # #


# # # C R E A T E # # #
class NewArea(generic.CreateView):
    template_name = 'core/area/create_a.html'
    model = models.Issue
    form_class = forms.NewAreaForm
    success_url = reverse_lazy('core:list_a')

# # # R E T R I E V E # # #
# # List
class ListArea(generic.ListView):
    template_name = "core/area/list_a.html"
    queryset = models.Issue.objects.filter(status=True)
# # Detail
class DetailArea(generic.DetailView):
    template_name = "core/area/detail_a.html"
    model = models.Area


# # # U P D A T E # # #
class UpdateArea(generic.UpdateView):
    template_name = "core/area/update_a.html"
    model = models.Area
    form_class = forms.UpdateAreaForm
    success_url = reverse_lazy("core:list_a")


# # # D E L E T E # # #
class DeleteArea(generic.DeleteView):
    template_name = "core/area/delete_a.html"
    model = models.Area
    form_class = forms.UpdateAreaForm
    success_url = reverse_lazy("core:list_a")

templates/core/goal/create_g.html
{% extends "base/base.html" %}

{% block title %} NEW GOAL VIEW {% endblock title %}

{% block content%}
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-success form-control">New Goal</button>
        <a href="{% url 'core:list_g' %}" class="btn btn-outline-warning form-control">
            Cancel
        </a>
    </form>
{% endblock content%}

templates/core/goal/delete_g.html
{% extends "base/base.html" %}

{% block title %}DELETE GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h2>¿Realmente deseas eliminar este Goal: <code>{{ object }}</code> ?</h2>
            
            <button type="submit" class="btn btn-outline-danger form-control">Delete Goal</button>
            <a href="{% url 'core:list_g' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/goal/detail_g.html
{% extends "base/base.html" %}

{% block title %}DETAIL GOAL VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Goal name is: <strong>{{ object.goalname }}</strong> and Its Description is: {{ object.description }}, the Responsable user is: <code>{{ object.user }}</code>.
          <strong>Its progress: {{ object.progress }}</strong>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The timestamp for the goal is: <strong>{{ object.timestamp }}.</strong> Its final date is: {{ object.final_date }} and its days duration:  <code>{{ object.days_duration }}</code>.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Status for the goal is: <strong>{{ object.status }}</strong> Its state is: {{ object.state }} and the priority is:  <code>{{ object.priority }}</code>.
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/core/goal/list_g.html
{% extends "base/base.html" %}

{% block title %}GOAL LIST VIEW{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col">
            <a href="{% url 'core:create_g' %}" class="btn btn-outline-success form-control">New Goal</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>USER</th>
            <th>SUBGRANTGOAL</th>
            <th>DAYSDURATION</th>
            <th>TIMESTAMP</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for goal in object_list %}
                <tr>
                    <td>{{ goal.id }}</td>
                    <td>{{ goal.goalname }}</td>
                    <td>{{ goal.user }}</td>
                    <td>{{ goal.subgrantgoal}}</td>
                    <td>{{ goal.days_duration }}</td>
                    <td>{{ goal.timestamp }}</td>
                    <td><a href="{% url 'core:detail_g' goal.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_g' goal.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_g' goal.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/core/goal/update_g.html
{% extends "base/base.html" %}

{% block title %}UPDATE GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-primary form-control">Update Goal</button>
            <a href="{% url 'core:list_g' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}